[package]
name = "taxi-data-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.38"
env_logger = "0.11.5"
log = "0.4.22"
rand = "0.8.5"
serde_json = "1.0.132"
